### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by NyTR0SGaM1NG** [joelamos/TFTunes#2]
with the latest version of windows and java i get a virtual machine error stating a java exception has occured.

**Comment by joelamos** [comment]
Have you downloaded the version I released about 2 hours ago? If not, do that first. Then run TFTunes using *run tftunes.bat*. Then post the error message. Thanks!

**Comment by NyTR0SGaM1NG** [comment]
that was the one i was having trouble with

**Comment by NyTR0SGaM1NG** [comment]
added on steam.

**Comment by joelamos** [comment]
Can you copy the exact error message from the command prompt and post it here? Also, did you have the first version up and running or was this a fresh install?
Search for "environment variables" in Windows, click the first results. Then click Environment variables. The look in System variables for an entry called Path. Select it and click edit. Look through the paths listed there and tell me if you see a path similar to "C:\Program Files\Java\jre1.8.0_60\bin" (it could be a different version).

**Comment by NyTR0SGaM1NG** [comment]
C:\Program Files (x86)\TFTunes>java -jar TFTunes.jar
Picked up _JAVA_OPTIONS: -Xmx512M
java.io.FileNotFoundException: properties\properties.txt (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at com.joelchristophel.tftunes.Properties.readProperties(Properties.java:426)
        at com.joelchristophel.tftunes.Properties.updateAndSyncProperties(Properties.java:395)
        at com.joelchristophel.tftunes.Properties.<init>(Properties.java:83)
        at com.joelchristophel.tftunes.Properties.getInstance(Properties.java:93)
        at com.joelchristophel.tftunes.Playlist.<clinit>(Playlist.java:34)
java.io.FileNotFoundException: properties\default properties (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at com.joelchristophel.tftunes.Properties.readProperties(Properties.java:426)
        at com.joelchristophel.tftunes.Properties.updateAndSyncProperties(Properties.java:397)
        at com.joelchristophel.tftunes.Properties.<init>(Properties.java:83)
        at com.joelchristophel.tftunes.Properties.getInstance(Properties.java:93)
        at com.joelchristophel.tftunes.Playlist.<clinit>(Playlist.java:34)
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: There are missing properties in "default properties".
        at com.joelchristophel.tftunes.Properties.readProperties(Properties.java:467)
        at com.joelchristophel.tftunes.Properties.updateAndSyncProperties(Properties.java:397)
        at com.joelchristophel.tftunes.Properties.<init>(Properties.java:83)
        at com.joelchristophel.tftunes.Properties.getInstance(Properties.java:93)
        at com.joelchristophel.tftunes.Playlist.<clinit>(Playlist.java:34)

fresh install of the first version.

**Comment by NyTR0SGaM1NG** [comment]
and thare is no such path.

**Comment by joelamos** [comment]
Thanks for the log! When I initially uploaded update 1.0.1, the zip did not have the properties folder inside. If you download once more, it will. Also, make sure you follow each step in the installation instructions before trying to run it. Let me know how it goes!

**Comment by joelamos** [comment]
This resolved the issue.
